apiVersion: v1
kind: Service
metadata:
  name: web-admin
  labels:
    app.kubernetes.io/name: web-admin
    app.kubernetes.io/component: admin-ui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web-admin
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
