// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: mpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MpcService_Keygen_FullMethodName = "/mpc.MpcService/Keygen"
	MpcService_Sign_FullMethodName   = "/mpc.MpcService/Sign"
)

// MpcServiceClient is the client API for MpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MpcServiceClient interface {
	// Generates a new distributed key share across the nodes.
	Keygen(ctx context.Context, in *KeygenRequest, opts ...grpc.CallOption) (*KeygenResponse, error)
	// Signs a message hash using the distributed key shares (Threshold Signature).
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
}

type mpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMpcServiceClient(cc grpc.ClientConnInterface) MpcServiceClient {
	return &mpcServiceClient{cc}
}

func (c *mpcServiceClient) Keygen(ctx context.Context, in *KeygenRequest, opts ...grpc.CallOption) (*KeygenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeygenResponse)
	err := c.cc.Invoke(ctx, MpcService_Keygen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpcServiceClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, MpcService_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MpcServiceServer is the server API for MpcService service.
// All implementations must embed UnimplementedMpcServiceServer
// for forward compatibility.
type MpcServiceServer interface {
	// Generates a new distributed key share across the nodes.
	Keygen(context.Context, *KeygenRequest) (*KeygenResponse, error)
	// Signs a message hash using the distributed key shares (Threshold Signature).
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	mustEmbedUnimplementedMpcServiceServer()
}

// UnimplementedMpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMpcServiceServer struct{}

func (UnimplementedMpcServiceServer) Keygen(context.Context, *KeygenRequest) (*KeygenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Keygen not implemented")
}
func (UnimplementedMpcServiceServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedMpcServiceServer) mustEmbedUnimplementedMpcServiceServer() {}
func (UnimplementedMpcServiceServer) testEmbeddedByValue()                    {}

// UnsafeMpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MpcServiceServer will
// result in compilation errors.
type UnsafeMpcServiceServer interface {
	mustEmbedUnimplementedMpcServiceServer()
}

func RegisterMpcServiceServer(s grpc.ServiceRegistrar, srv MpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedMpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MpcService_ServiceDesc, srv)
}

func _MpcService_Keygen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeygenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MpcServiceServer).Keygen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MpcService_Keygen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MpcServiceServer).Keygen(ctx, req.(*KeygenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MpcService_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MpcServiceServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MpcService_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MpcServiceServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MpcService_ServiceDesc is the grpc.ServiceDesc for MpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpc.MpcService",
	HandlerType: (*MpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Keygen",
			Handler:    _MpcService_Keygen_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _MpcService_Sign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mpc.proto",
}
