apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kerosene-production
resources:
  - ../../base
  - namespace.yaml
labels:
  - pairs:
      app.kubernetes.io/environment: production
images:
  - name: kerosene/kerosene-app
    newTag: replace-me
  - name: kerosene/mpc-sidecar
    newTag: replace-me
  - name: kerosene/web-admin
    newTag: replace-me
patches:
  - path: patch-production-resources.yaml
  - path: patch-production-storage.yaml
  - path: patch-production-config.yaml
