apiVersion: apps/v1
kind: Deployment
metadata:
  name: kerosene-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: kerosene-app
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kerosene-app
spec:
  minReplicas: 3
  maxReplicas: 12
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-admin
spec:
  replicas: 2
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kerosene-app
spec:
  minAvailable: 2
