apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kerosene-bitcoin
  namespace: kerosene-production
spec:
  serviceName: kerosene-bitcoin-headless
  replicas: 1
  selector:
    matchLabels:
      app: kerosene-bitcoin
  template:
    metadata:
      labels:
        app: kerosene-bitcoin
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: bitcoind
        image: lncm/bitcoind:v27.0
        command:
        - "bitcoind"
        - "-conf=/bitcoin/bitcoin.conf"
        - "-datadir=/data"
        - "-rpcuser=$(BITCOIN_RPC_USER)"
        - "-rpcpassword=$(BITCOIN_RPC_PASSWORD)"
        env:
        - name: BITCOIN_RPC_USER
          valueFrom:
            secretKeyRef:
              name: kerosene-bitcoin-secrets
              key: rpc-user
        - name: BITCOIN_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kerosene-bitcoin-secrets
              key: rpc-password
        ports:
        - containerPort: 8332
          name: rpc
        - containerPort: 8333
          name: p2p
        - containerPort: 28332
          name: zmq-block
        - containerPort: 28333
          name: zmq-tx
        volumeMounts:
        - name: bitcoin-data
          mountPath: /data
        - name: bitcoin-config
          mountPath: /bitcoin
      volumes:
      - name: bitcoin-config
        configMap:
          name: bitcoin-config
  volumeClaimTemplates:
  - metadata:
      name: bitcoin-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-luks-encrypted"
      resources:
        requests:
          storage: 1000Gi # Requires at least 1TB for Mainnet Archival
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoin-config
  namespace: kerosene-production
data:
  bitcoin.conf: |
    chain=main
    server=1
    txindex=1
    bind=0.0.0.0
    rpcbind=0.0.0.0
    rpcallowip=10.0.0.0/8
    zmqpubrawblock=tcp://0.0.0.0:28332
    zmqpubrawtx=tcp://0.0.0.0:28333
    dbcache=2048
    maxmempool=500
    maxconnections=40
