apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kerosene-app
  labels:
    app.kubernetes.io/name: kerosene-app
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: kerosene-app
