apiVersion: v1
kind: Service
metadata:
  name: kerosene-app
  labels:
    app.kubernetes.io/name: kerosene-app
    app.kubernetes.io/component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kerosene-app
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
